#!/usr/bin/env python3
"""One-line factual descriptions for tools (used in YAML `about` and browse.md)."""

# Factual product descriptions for student scanning—not discount text.
TOOL_ABOUT: dict[str, str] = {
    "adobe-creative-cloud-pro": "Creative Cloud apps for photo, video, and design (e.g. Photoshop, Premiere).",
    "appwrite-education": "Open-source backend for apps—auth, databases, storage, and serverless functions.",
    "autodesk-education": "CAD and 3D software for engineering and media (AutoCAD, Fusion, Maya, and more).",
    "aws-educate": "Free AWS cloud learning paths, labs, and badges for students.",
    "aws-education-equity-initiative": "AWS cloud credits for eligible edtech and nonprofit equity programs.",
    "aws-education-programs": "Entry point for AWS student and educator cloud programs.",
    "beautiful-ai-education": "AI-assisted slide decks and presentation design in the browser.",
    "camber": "Cloud notebooks for data science and ML coursework.",
    "canva-education": "Browser design tool for graphics, slides, and classroom visuals (K–12 focus).",
    "carto-student-pack": "Cloud mapping, geospatial data, and location analytics.",
    "chatgpt-edu": "Campus-wide ChatGPT for universities—sold to institutions, not individual checkout.",
    "cocounsel-law-school": "Thomson Reuters generative AI for legal research and drafting in law school.",
    "consensus": "AI search over scientific papers with cited summaries.",
    "coursera-campus": "University site license for Coursera courses and credentials.",
    "cursor": "AI code editor with chat and inline code generation (VS Code–style).",
    "datacamp-student": "Interactive courses for Python, R, SQL, and data science.",
    "deepnote": "Collaborative data notebooks in the browser for teams and classes.",
    "descript": "Edit podcasts and video by editing text; AI voices and transcription.",
    "digitalocean-student-pack": "Cloud servers (Droplets) and hosting credits for developers.",
    "duolingo-for-schools": "Teacher dashboard and classroom tools on top of Duolingo.",
    "edpuzzle": "Add questions and track progress inside video lessons.",
    "educative": "Text-based interactive coding courses and skill paths.",
    "elevenlabs": "Realistic AI voice generation and text-to-speech.",
    "figma-education": "Collaborative UI/UX design, prototyping, and design systems.",
    "github-codespaces": "Full dev environments in the browser, launched from GitHub repos.",
    "github-copilot-student": "AI code suggestions and chat inside your IDE (GitHub).",
    "github-education-experiences": "Short guided learning modules on GitHub tools and Copilot.",
    "github-student-developer-pack": "Bundle of free dev tools, domains, and cloud credits for students.",
    "google-ai-pro-students": "Google Gemini advanced features in Google apps (student offer).",
    "google-cloud-education-grants": "Faculty-requested Google Cloud credits for university courses.",
    "grammarly-education": "Writing and grammar help deployed across a school or university.",
    "harvey-academy": "Free online courses on legal AI from Harvey.",
    "harvey-law-school-program": "Harvey legal AI workspace through participating law schools.",
    "huggingface-academia-hub": "Team Hub for sharing ML models, datasets, and compute (institutions).",
    "icons8-student-pack": "Icons, stock photos, illustrations, and music for projects.",
    "iconscout-student-pack": "Icons and design assets from a large marketplace.",
    "jetbrains-student-pack": "Free professional IDEs—IntelliJ, PyCharm, WebStorm, and others.",
    "khanmigo": "Khan Academy AI guide for teaching and learning math and more.",
    "lexis-plus-ai-law-schools": "Lexis+ legal research with generative AI for law students (US).",
    "loom": "Quick screen-and-camera videos for async updates and tutorials.",
    "microsoft-365-college-students": "Word, Excel, PowerPoint, Teams, and cloud storage for college students.",
    "microsoft-azure-students": "Microsoft Azure cloud credits and free services for students.",
    "microsoft-copilot-education": "Microsoft 365 Copilot for schools on education licenses.",
    "microsoft-education-students": "Overview of Microsoft student offers (Azure, tools, learning).",
    "miro-education": "Infinite whiteboard for workshops, planning, and group work.",
    "murf-ai": "AI voiceovers and narration for videos and presentations.",
    "notion-education": "All-in-one notes, docs, and wikis with AI features.",
    "notion-student-pack": "Notion education plan via GitHub Pack (extra AI quota).",
    "obsidian-education": "Local-first Markdown notes; discount on Sync and Publish add-ons.",
    "openai-codex-students": "Credits for OpenAI Codex coding agent in ChatGPT.",
    "openai-researcher-access": "Subsidized OpenAI API credits for academic research projects.",
    "otter-ai": "Record meetings and get searchable transcripts and summaries.",
    "perplexity": "AI answers with live web search and source citations.",
    "popsql-student-pack": "Collaborative SQL editor for writing and sharing queries.",
    "quillbot": "Paraphrase, summarize, and check grammar in your writing.",
    "quizlet-for-schools": "School-wide Quizlet Plus—flashcards, study modes, and AI study aids.",
    "replit": "Code in the browser with hosting and an AI coding agent.",
    "reverso-premium-education": "Translation, definitions, and document translation (Reverso).",
    "runway": "AI video generation, editing, and effects for creators.",
    "slack-education": "Team chat and channels for classes, clubs, and projects.",
    "slidecoach": "AI feedback on how you deliver presentations.",
    "visme-student-pack": "Presentations, infographics, and simple visual content.",
    "westlaw-law-school": "Legal research platform included with many law school subscriptions.",
    "windsurf": "AI code editor with agent-style multi-step coding (from Codeium).",
    "wolfram-alpha-pro-students": "Step-by-step math, science, and data computation help.",
    "wordtune": "Rewrite sentences and adjust tone with AI suggestions.",
    "writesonic": "Generate marketing copy, blogs, and ads with AI.",
    "zoom-workplace-education": "Video meetings, webinars, and classroom collaboration for schools.",
}
